name: qsvm-vm-compare
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - numpy
  - scikit-learn
  - psutil=5.9.*
  - pip:
      - pennylane>=0.45,<0.46
      - pennylane-lightning-gpu>=0.45,<0.46
      - cuquantum-cu12
      - cuquantum-python-cu12
      - custatevec-cu12
      - -e .
